# list of meta tags
- property: "og:title" 
  content: Sina Dehghanian
- property: "og:site_name" 
  content: Sina Dehghanian's webpage
- property: "og:description"
  content: Data Analyst | BI Developer 📈📊📉</br>Data Career Path Mentor
- property: "og:type" 
  content: profile
- property: "og:locale" 
  content: en_US
- property: "og:url" 
  content: https://sinad.me/
- property: "og:image" 
  content: "https://avatars.githubusercontent.com/u/74854551?v:4"
- property: "og:image:secure_url" 
  content: "https://avatars.githubusercontent.com/u/74854551?v:4"
- property: "og:image:width" 
  content: 50
- property: "og:image:height" 
  content: 50
- property: "og:image:type" 
  content: "image/png"
- property: "profile:first_name" 
  content: Sina
- property: "profile:last_name" 
  content: Dehghanian
- property: "profile:gender" 
  content: male
- name: keywords
  content: Sina Dehghanian, Isfahan University of Technology, Sina, Dehghanian, Data Analyst, Data Analysis, SQL, Python, git, fog computing, cloud computing, reinforcement learning, Revolut, Roomvu, Digikala, پردازش مبتنی بر مه, پردازش مه, رایانش مبتنی بر مه, رایانش مه, رایانش مهی, رایانش ابری, سینا دهقانیان, دانشگاه صنعتی اصفهان
- name: author
  content: Sina Dehghanian
- name: robots
  content: index, follow
- name: revisit-after
  content: 15 days
- name: language
  content: English
- name: google-site-verification
  content: wWUFZdsK_Z4_Dc7uB1Wnny-v1CRnVjDGKr3asuyKzdU