title: Sina Dehghanian
logo: https://avatars.githubusercontent.com/u/74854551?v=4
subtitle: Data Analyst and Data Engineer 📈📊🧰
# description:
favicon: true
color-scheme: auto
url: "https://sinad.me"

google_analytics: G-BSG5E6YK09

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

platforms:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/DehghanianSina
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: https://www.linkedin.com/in/SinaDehghanian
  - name: Telegram
    icon: <i class="fa-brands fa-telegram"></i>
    link: https://t.me/Dehghanian_Sina
  - name: Links
    icon: <i class="fa-solid fa-link"></i>
    link: /links/
  - name: CV
    icon: <i class="fa-regular fa-file-pdf"></i>
    link: /assets/files/SinaDehghanian_DataAnalyst-Engineer_CV_v2025-08.pdf
    target: _blank

navigation:
  - name:  About Me
    link: /#about-me
    icon: <i class="fa-solid fa-info"></i> 
  - name: Work Experiences
    link: /#work-experiences
    icon: <i class="fa-solid fa-briefcase"></i>
  - name: Education
    link: /#education
    icon: <i class="fa-solid fa-graduation-cap"></i>
  - name: Academic Experiences
    link: /#academic-experiences
    icon: <i class="fa-solid fa-chalkboard-user"></i>
  - name: Volunteer Experiences
    link: /#volunteer-experiences
    icon: <i class="fas fa-hands-helping"></i>
  - name: Skills
    link: /#skills
    icon: <i class="fa-solid fa-laptop-code"></i>
  - name: Honors
    link: /#honors
    icon: <i class="fa-solid fa-award"></i>

meta:
- property: og:description
  content: "Checkout Sina Dehghanian's journey, the meticulous Data Analyst, Data Engineer, and Mentor\
    \ \U0001F4C8\U0001F4CA\U0001F4C9"
- property: og:image
  content: https://avatars.githubusercontent.com/u/74854551?v:4
- property: og:image:secure_url
  content: https://avatars.githubusercontent.com/u/74854551?v:4
- property: og:image:width
  content: 50
- property: og:image:height
  content: 50
- property: og:image:type
  content: image/png
- property: profile:first_name
  content: Sina
- property: profile:last_name
  content: Dehghanian
- property: profile:gender
  content: male

link:
  rel: canonical
  href: https://sinad.me/